apiVersion: v1
kind: Pod
metadata:
  name: controller-pod
  labels:
    app: controller-app
spec:
  containers:
    - name: controller-pod
      image: cr.yandex/crplcjja2vnksfnhmpdj/controller:latest
      imagePullPolicy: Always
      ports:
        - name: controller-pod
          containerPort: 80
          protocol: TCP
      env:
        - name: PROMETHEUS_HOST
          value: http://10.1.129.21:9090
  restartPolicy: Always
  